version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./server/.env.docker
    volumes:
      - ./sql/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
      - ./sql/trivia_data.sql:/docker-entrypoint-initdb.d/trivia_data.sql:ro
      - ./sql/02_load_data.sh:/docker-entrypoint-initdb.d/02_load_data.sh:ro
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./server
    depends_on:
      - db
    env_file:
      - ./server/.env.docker
    environment:
      - FLASK_APP=__init__:app
    ports:
      - "5000:5000"
    restart: always

volumes:
  db_data:
    driver: local